server:
  port: 8083

spring:
  application:
    name: api-gateway
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

admin:
  service:
    url: http://localhost:8080