server:
  port: 8082

admin:
  service:
    url : http://localhost:8080

spring:
  security:
    user:
      name: admin
      password: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

resilience4j:
  circuitbreaker:
    instances:
      adminService:
        failure-rate-threshold: 50  # Trip circuit after 50% failures
        minimum-number-of-calls: 1  # Minimum calls before evaluating
        sliding-window-size: 10      # Last 10 calls determine state
        wait-duration-in-open-state: 10s  # Time before retrying