spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

resilience4j.circuitbreaker:
  instances:
    seller-service:
      register-health-indicator: true
      sliding-window-type: COUNT_BASED
      sliding-window-size: 10
      minimum-number-of-calls: 5
      permitted-number-of-calls-in-half-open-state: 3
      automatic-transition-from-open-to-half-open-enabled: true
      wait-duration-in-open-state: 10s
      failure-rate-threshold: 50
      event-consumer-buffer-size: 10
      record-exceptions:
        - org.springframework.web.client.ResourceAccessException
        - java.lang.RuntimeException